server:
    port: 8080
---
spring:
    application:
        name: spotify-service
    datasourse:
        url: jdbc:h2:file:c:/data/demo
        username: sa
        password: password
        driverClassname: org.h2.Driver
    jpa:
        spring.jpa.database-plataform: org.hibernate.dialect.H2Dialect
        hibernate:
            dll-auto: update
    h2:
        console.enabled: true


